# Generated by Django 4.2.1 on 2023-07-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobFinder', '0005_alter_vagas_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vagas',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
